language: haskell
ghc:
  - 7.4
  - 7.6
  - 7.8
notifications:
  email: false
before_script:
  - cabal sdist
  - mkdir travisbuild
  - mv dist/binary-list*.tar.gz travisbuild/code.tar.gz
  - cd travisbuild
  - tar xzvf code.tar.gz
  - cd binary-list*
script:
  - cabal configure --enable-tests --ghc-option=-Werror
  - cabal build
  - cabal test
